name: Deploy Frontend to S3

on:
  push:
    branches:
      - main
      - frontend
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd test
          npm install

      - name: Build frontend
        run: |
          cd test
          npm run build

      - name: Sync build to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        env:
          AWS_S3_BUCKET: "milkybloom-frontend"                 # üí• G√ÅN C·ª®NG
          AWS_REGION: "us-east-1"                              # üí• G√ÅN C·ª®NG
          AWS_ACCESS_KEY_ID: "AKIAVBF5CKFATC75YONX"       # üí• G√ÅN C·ª®NG
          AWS_SECRET_ACCESS_KEY: "eNMNifkBc+BqP5Kg/hEiEBbtA9Cq2XUORVQchDzg"       # üí• G√ÅN C·ª®NG
          SOURCE_DIR: "test/dist"
        with:
          args: --delete

      - name: Invalidate CloudFront cache
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: "E3ABCDEFG12345"        # üí• G√ÅN C·ª®NG
          PATHS: "/*"                                          
          AWS_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: "AKIAVBF5CKFATC75YONX"       # üí• G√ÅN C·ª®NG
          AWS_SECRET_ACCESS_KEY: "eNMNifkBc+BqP5Kg/hEiEBbtA9Cq2XUORVQchDzg"       # üí• G√ÅN C·ª®NG
